parameters:
    auth_provider_area: 'blog'

services:
    # Репозиторий пользователей
    temirkhan.user.repository.user:
        class: Temirkhan\UserBundle\Repository\UserRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    # Сервис аутентификации
    temirkhan.user.service.auth:
        class: Temirkhan\UserBundle\Service\AuthService
        arguments:
            - '@temirkhan.user.service.auth_provider'
            - '%auth_provider_area%'
            - '@security.token_storage'

    # Сервис пользователей
    temirkhan.user.service.user:
        class: Temirkhan\UserBundle\Service\UserService
        arguments:
            - '@temirkhan.user.repository.user'
            - '@security.encoder_factory'

    # Провайдер пользователей
    temirkhan.user.provider.user:
        class: Temirkhan\UserBundle\Provider\UserProvider
        arguments:
            - '@temirkhan.user.repository.user'
            - '@security.encoder_factory'

    # Провайдер аутентификации
    temirkhan.user.service.auth_provider:
        class: Symfony\Component\Security\Core\Authentication\Provider\DaoAuthenticationProvider
        arguments:
            - '@temirkhan.user.provider.user'
            - '@security.user_checker'
            - '%auth_provider_area%'
            - '@security.encoder_factory'