services:
    # Репозиторий пользователей
    temirkhan.user.repository.user:
        class: Temirkhan\UserBundle\Repository\UserRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    # Сервис пользователей
    temirkhan.user.service.user:
        class: Temirkhan\UserBundle\Service\UserService
        arguments:
            - '@temirkhan.user.repository.user'