version: '2'
services:
  frontend:
    image: nginx
    volumes:
      - ./:/var/www/html
      - ./docker/blog-nginx.template:/etc/nginx/conf.d/blog.template
    ports:
      - "81:80"
    links:
      - db
      - backend
    depends_on:
      - db
      - backend
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/blog.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  backend:
    build: ./
    volumes:
      - ./:/var/www/html
  db:
    image: sameersbn/postgresql
    environment:
      - DB_USER=blog
      - DB_PASS=some_pass
      - DB_NAME=blog_db