version: '2'
services:
  db:
    image: sameersbn/postgresql
    environment:
      - DB_USER=blog
      - DB_PASS=some_pass
      - DB_NAME=blog_db
  frontend:
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
    ports:
      - "81:80"
    links:
      - backend
    depends_on:
      - backend
    command: sh -c "envsubst '' < /var/www/html/docker/blog-nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  backend:
    build: ./
    volumes:
      - ./:/var/www/html
    links:
      - db
    depends_on:
      - db
    command: sh -c "chmod +x ./docker/wait-for-it.sh && ./docker/wait-for-it.sh"