version: '2'
services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
    ports:
      - "81:80"
    links:
      - db
      - backend
    depends_on:
      - db
      - backend
    command: sh -c "envsubst '' < /var/www/html/docker/blog-nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  backend:
    build: ./
    volumes:
      - ./:/var/www/html
    command: sh -c "cd /var/www/html && composer install --prefer-source --no-interaction && rm -rf var/cache/* && chown -R www-data:www-data ./var && php-fpm -F"
  db:
    image: sameersbn/postgresql
    environment:
      - DB_USER=blog
      - DB_PASS=some_pass
      - DB_NAME=blog_db