# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        session_provider:
            memory: ~
        blog_user_provider:
            id: temirkhan.user.provider.user
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        blog:
            anonymous: ~
            provider: blog_user_provider
            pattern: ^/
            logout:
                path: /logout
                target: /