#Страница решистрации
blog_register:
    path: /registration
    defaults: { _controller: blog.controller.author.register:execute }

# Страница входа
blog.login:
    path: /login
    defaults: { _controller: blog.controller.auth.login:execute }

#Основая страница блога со списком публикаций
blog_posts:
    path: /{page}
    defaults: { _controller: blog.controller.post.list:execute }
    requirements:
        page: '[1-9][0-9]*'

#Страница с публикациями автора
author_posts:
    path: /author-{author}/{page}
    defaults: { _controller: blog_bundle.controller.post:getAuthorContentsAction, page: 1, onPage: 10 }
    requirements:
        page: '[1-9][0-9]*'
        author: '[1-9][0-9]*'
        onPage: '[1-9][0-9]*'

#Страница с публикацией
blog_post:
    path: /posts/{post}
    defaults: { _controller: blog_bundle.controller.post:getContentAction }
    requirements:
        post: '[1-9][0-9]*'

#Страница добавления публикации
add_post:
    path: /post/add
    defaults: { _controller: blog.controller.create_post:execute }
    methods: [POST, GET]

#Страница редактирования публикации
edit_post:
    path: /post-{postId}/edit
    defaults: { _controller: blog_bundle.controller.post:updateContentAction }
    requirements:
        postId: '[1-9][0-9]*'

#Страница выноса публикаций из черновиков в опубликованные
publish_post:
    path: /post-{postId}/publish
    defaults: { _controller: blog_bundle.controller.post:publishContentAction }
    requirements:
        postId: '[1-9][0-9]*'

#Страница удаления публикации
delete_post:
    path: /post-{postId}/delete
    defaults: { _controller: blog_bundle.controller.post:deleteContentAction }
    requirements:
        postId: '[1-9][0-9]*'

#Страница добавления комментария к публикации
add_comment:
    path: /comment/add/post-{postId}
    defaults: { _controller: BlogBundle:Comment:createComment }
    requirements:
        postId: '[1-9][0-9]*'