#Страница решистрации
blog_register:
    path: /register
    defaults: { _controller: blog_bundle.controller.user:registerAction }

#Страница входа
blog_login:
    path: /login
    defaults: { _controller: blog_bundle.controller.user:loginAction }

#Страница выхода
blog_logout:
    path: /logout
    defaults: { _controller: blog_bundle.controller.user:logoutAction }

#Основая страница блога со списком публикаций
blog_posts:
    path: /{page}
    defaults: { _controller: blog_bundle.controller.post:indexAction, page: 1, onPage: 10 }
    requirements:
        page: \d+

#Страница с публикациями автора
author_posts:
    path: /author-{author}/{page}
    defaults: { _controller: blog_bundle.controller.post:getAuthorContentsAction, page: 1, onPage: 10 }
    requirements:
        page: \d+
        author: \d+
        onPage: \d+

#Страница с отдельной публикацией
blog_post:
    path: /post-{post}
    defaults: { _controller: blog_bundle.controller.post:getContentAction }
    requirements:
        post: \d+

#Страница добавления публикации
add_post:
    path: /post/add
    defaults: { _controller: blog_bundle.controller.post:createContentAction }

#Страница редактирования публикации
edit_post:
    path: /post-{postId}/edit
    defaults: { _controller: blog_bundle.controller.post:updateContentAction }
    requirements:
        postId: \d+

#Страница выноса публикаций из черновиков в опубликованные
publish_post:
    path: /post-{postId}/publish
    defaults: { _controller: blog_bundle.controller.post:publishContentAction }
    requirements:
        postId: \d+

#Страница удаления публикации
delete_post:
    path: /post-{postId}/delete
    defaults: { _controller: blog_bundle.controller.post:deleteContentAction }
    requirements:
        postId: \d+

#Страница добавления комментария к публикации
add_comment:
    path: /comment/add/post-{postId}
    defaults: { _controller: BlogBundle:Comment:createComment }
    requirements:
        postId: \d+