services:
    # Контроллер создания публикаций
    blog.controller.create_post:
        class: BlogBundle\Controller\Post\CreateController
        arguments:
            - '@templating'
            - '@form.factory'
            - '@blog.service.post'
            - '@router'

    # Контроллер выхода из системы
    blog.controller.logout:
        class: BlogBundle\Controller\Auth\LogoutController
        arguments:
            - '@templating'

    # Репозиторий публикаций
    blog.repository.post:
        class: Temirkhan\BlogBundle\Repository\PostRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    # Сервис публикаций
    blog.service.post:
        class: Temirkhan\Blog\Service\PostService
        arguments:
            - '@blog.repository.post'