imports:
    - { resource: controllers.yml }
    - { resource: repositories.yml }

services:
    # Сервис авторов
    blog.service.author:
        class: BlogBundle\Service\AuthorService
        arguments:
            - '@temirkhan.user.service.user'
            - '@blog.repository.author'

    # Сервис публикаций
    blog.service.post:
        class: Temirkhan\Blog\Service\PostService
        arguments:
            - '@blog.repository.post'