imports:
    - { resource: controllers.yml }
    - { resource: event-listeners.yml }
    - { resource: param-converters.yml }
    - { resource: repositories.yml }
    - { resource: voters.yml }
parameters:
    # Число публикаций на страницу
    default_per_page_posts_count: 5

services:
    # Сервис авторов
    blog.service.author:
        class: BlogBundle\Service\AuthorService
        arguments:
            - '@temirkhan.user.service.user'
            - '@blog.repository.author'

    # Сервис публикаций
    blog.service.post:
        class: Temirkhan\Blog\Service\PostService
        arguments:
            - '@blog.repository.post'